### ISSUE TITLE
[Suggestion] Add backup champ picks in arena mode in case main pick is banned or picked

### ISSUE THREAD

**Issue by LLjo** [sweetriverfish/LeagueAutoAccept#49] opened 2024-07-31 18:25 UTC
Great project! Many thanks, this works well in Arena mode. Just wondering if it's possible to get an arena mode version?

**Comment by sweetriverfish** [comment] 2024-08-01 11:38
This is just a duplicate of #15

**Closed as completed by sweetriverfish** 2024-08-01 11:38 UTC
